# Generated by Django 5.0.2 on 2024-03-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancing_places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
