# Generated by Django 5.0.2 on 2024-03-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancing_places', '0002_spot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
